API for the members' page
kgpmask/MASK-Next pull request #6
Opened 2023-12-25 07:38 UTC by Signor-Koala

2023-12-25 19:07 UTC, destryptor approved these changes

2023-12-26 03:32 UTC, Goose-Of-War requested changes
Fix these things n.n

2023-12-26 03:32 UTC, Goose-Of-War commented on utils/database/dbHandler.ts
![image](https://github.com/kgpmask/MASK-Next/assets/64352864/e2484e75-d752-4e60-8e75-2d44e5bc80c7)

2023-12-26 03:32 UTC, Goose-Of-War commented on pages/api/members.ts
No need to store the value returned by `await dbConnect();` in a variable. Just call it and let it be.

Also, please use a full variable name such as `members` instead of `m`

2023-12-26 03:55 UTC, Goose-Of-War commented
Also, one more thing. Can you yeet dbHandler and directly implement the function in the route? We won't be using the function in multiple places, so direct handler method for now :?

2023-12-26 05:55 UTC, closed without merging