TextArea Components and Static Text Pages
kgpmask/MASK-Next pull request #7
Opened 2023-12-25 09:49 UTC by ItsAnkan

This PR has the components for static text pages, and the converted pages using those components

Covers `/terms`, `/privacy`, `/about` and `/events/[event-name]`

2023-12-25 10:36 UTC, Goose-Of-War reviewed
Shameless copying of the base components, eh?

2023-12-25 10:39 UTC, ItsAnkan commented
I edited much stuff ;-;

2023-12-25 10:40 UTC, Goose-Of-War commented
![image](https://github.com/kgpmask/MASK-Next/assets/64352864/51d6d8d5-ed22-4814-adf0-994a0ba40996)
_smile in pain: Ankan edition_

2023-12-25 10:40 UTC, Goose-Of-War commented
That should explain why there no images in OACQ

2023-12-25 10:42 UTC, ItsAnkan commented
Fixed

2023-12-25 10:44 UTC, ItsAnkan commented
Fixed

2023-12-25 10:51 UTC, Goose-Of-War commented
Event pages are missing headings -_-

2023-12-25 10:52 UTC, Goose-Of-War commented
Also, why you clone HeadContent component if you ain't using it everywhere...

2023-12-25 10:52 UTC, Goose-Of-War commented
SMH

2023-12-26 03:37 UTC, Goose-Of-War commented
You forgot Cosplay 23 ;-;

2023-12-26 03:39 UTC, Goose-Of-War requested changes
fix onegai

2023-12-26 03:39 UTC, Goose-Of-War commented on pages/events/cosplay23.tsx
Heading where?

2023-12-26 07:11 UTC, Goose-Of-War approved these changes
I blame Ankan if anything breaks

2023-12-26 07:11 UTC, merged